spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/securityRedis
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.Oracle10gDialect
        #        show_sql: true  #print로 남김
        format_sql: true

logging.level:
  com.example.springsecurityredis: debug
  org.springframework: debug
#  org.hibernate.SQL: debug #log로 남김
#  org.hibernate.type: trace #parameter보기