spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.Oracle10gDialect
        #        show_sql: true  #print로 남김
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: true
  session:
    store-type: redis
  redis:
#    host: 127.0.0.1
    host: 34.80.121.167
    password:
    port: 6379

logging.level:
  com.example.springsecurityredis: debug
#  org.springframework: debug
#  org.hibernate.SQL: debug #log로 남김
#  org.hibernate.type: trace #parameter보기

#server:
#  port: 9000
